# main text of home
name: Yuxuan Zhang
bio: A Girl who travels the world eating noodles

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: https://zhangyuxuan1996.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
github: https://github.com/zhangyuxuan1996
#email: me@jane.doe

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
